[project]
name = "whatenc"
version = "0.3.1"
description = "Simple text encoding type classifier"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "onnxruntime>=1.23.2",
]

[project.urls]
Homepage = "https://github.com/jeremyctrl/whatenc"
Repository = "https://github.com/jeremyctrl/whatenc"
Issues = "https://github.com/jeremyctrl/whatenc/issues"

[project.optional-dependencies]
dev = [
    "build>=1.3.0",
    "twine>=6.2.0",
]

train = [
    "datasets>=4.3.0",
    "scikit-learn>=1.7.2",
    "skl2onnx>=1.19.1",
    "joblib>=1.5.2",
]

[project.scripts]
whatenc = "whatenc.cli:main"

[tool.setuptools]
packages = ["whatenc"]
include-package-data = true

[tool.setuptools.data-files]
models = ["models/model.onnx"]
